version: '3.8'

services:
  tunevault-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tunevault-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuneVault@2026!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - tunevault_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  tunevault_data:
